require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FieldsSellersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FieldsSeller. As you add validations to FieldsSeller, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FieldsSellersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all fields_sellers as @fields_sellers" do
      fields_seller = FieldsSeller.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fields_sellers)).to eq([fields_seller])
    end
  end

  describe "GET #show" do
    it "assigns the requested fields_seller as @fields_seller" do
      fields_seller = FieldsSeller.create! valid_attributes
      get :show, {:id => fields_seller.to_param}, valid_session
      expect(assigns(:fields_seller)).to eq(fields_seller)
    end
  end

  describe "GET #new" do
    it "assigns a new fields_seller as @fields_seller" do
      get :new, {}, valid_session
      expect(assigns(:fields_seller)).to be_a_new(FieldsSeller)
    end
  end

  describe "GET #edit" do
    it "assigns the requested fields_seller as @fields_seller" do
      fields_seller = FieldsSeller.create! valid_attributes
      get :edit, {:id => fields_seller.to_param}, valid_session
      expect(assigns(:fields_seller)).to eq(fields_seller)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FieldsSeller" do
        expect {
          post :create, {:fields_seller => valid_attributes}, valid_session
        }.to change(FieldsSeller, :count).by(1)
      end

      it "assigns a newly created fields_seller as @fields_seller" do
        post :create, {:fields_seller => valid_attributes}, valid_session
        expect(assigns(:fields_seller)).to be_a(FieldsSeller)
        expect(assigns(:fields_seller)).to be_persisted
      end

      it "redirects to the created fields_seller" do
        post :create, {:fields_seller => valid_attributes}, valid_session
        expect(response).to redirect_to(FieldsSeller.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved fields_seller as @fields_seller" do
        post :create, {:fields_seller => invalid_attributes}, valid_session
        expect(assigns(:fields_seller)).to be_a_new(FieldsSeller)
      end

      it "re-renders the 'new' template" do
        post :create, {:fields_seller => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fields_seller" do
        fields_seller = FieldsSeller.create! valid_attributes
        put :update, {:id => fields_seller.to_param, :fields_seller => new_attributes}, valid_session
        fields_seller.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fields_seller as @fields_seller" do
        fields_seller = FieldsSeller.create! valid_attributes
        put :update, {:id => fields_seller.to_param, :fields_seller => valid_attributes}, valid_session
        expect(assigns(:fields_seller)).to eq(fields_seller)
      end

      it "redirects to the fields_seller" do
        fields_seller = FieldsSeller.create! valid_attributes
        put :update, {:id => fields_seller.to_param, :fields_seller => valid_attributes}, valid_session
        expect(response).to redirect_to(fields_seller)
      end
    end

    context "with invalid params" do
      it "assigns the fields_seller as @fields_seller" do
        fields_seller = FieldsSeller.create! valid_attributes
        put :update, {:id => fields_seller.to_param, :fields_seller => invalid_attributes}, valid_session
        expect(assigns(:fields_seller)).to eq(fields_seller)
      end

      it "re-renders the 'edit' template" do
        fields_seller = FieldsSeller.create! valid_attributes
        put :update, {:id => fields_seller.to_param, :fields_seller => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested fields_seller" do
      fields_seller = FieldsSeller.create! valid_attributes
      expect {
        delete :destroy, {:id => fields_seller.to_param}, valid_session
      }.to change(FieldsSeller, :count).by(-1)
    end

    it "redirects to the fields_sellers list" do
      fields_seller = FieldsSeller.create! valid_attributes
      delete :destroy, {:id => fields_seller.to_param}, valid_session
      expect(response).to redirect_to(fields_sellers_url)
    end
  end

end
